// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMHi0vRHBhxQcoP_y8cVvaqzddCgtH1w',
    appId: '1:890103104330:web:a80e94ad7b1fdcdb6b77b3',
    messagingSenderId: '890103104330',
    projectId: 'asistencia-empresa-c0a16',
    authDomain: 'asistencia-empresa-c0a16.firebaseapp.com',
    storageBucket: 'asistencia-empresa-c0a16.firebasestorage.app',
    measurementId: 'G-TY4CRSC80B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgVqB7xR1SK0yjDiBDbGvHj-9s8stYugw',
    appId: '1:890103104330:android:5ddac198a82632756b77b3',
    messagingSenderId: '890103104330',
    projectId: 'asistencia-empresa-c0a16',
    storageBucket: 'asistencia-empresa-c0a16.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgS-uwDaPgyIjsDbcDFAFYKTQlVECbffQ',
    appId: '1:890103104330:ios:bf19601adf051f4c6b77b3',
    messagingSenderId: '890103104330',
    projectId: 'asistencia-empresa-c0a16',
    storageBucket: 'asistencia-empresa-c0a16.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgS-uwDaPgyIjsDbcDFAFYKTQlVECbffQ',
    appId: '1:890103104330:ios:bf19601adf051f4c6b77b3',
    messagingSenderId: '890103104330',
    projectId: 'asistencia-empresa-c0a16',
    storageBucket: 'asistencia-empresa-c0a16.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFMHi0vRHBhxQcoP_y8cVvaqzddCgtH1w',
    appId: '1:890103104330:web:43d4732293278cc66b77b3',
    messagingSenderId: '890103104330',
    projectId: 'asistencia-empresa-c0a16',
    authDomain: 'asistencia-empresa-c0a16.firebaseapp.com',
    storageBucket: 'asistencia-empresa-c0a16.firebasestorage.app',
    measurementId: 'G-6LFGYHECBD',
  );
}
