// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-s477TNVXm7uKDxIx_EiMC1PvwW7FCVY',
    appId: '1:849051826489:web:6fd932c37ac91857a110e8',
    messagingSenderId: '849051826489',
    projectId: 'control-asistencia-f6eb5',
    authDomain: 'control-asistencia-f6eb5.firebaseapp.com',
    storageBucket: 'control-asistencia-f6eb5.firebasestorage.app',
    measurementId: 'G-DQ1N096WFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFV8VJUqbHWLUvg_s6tKe6BifBQvpuzk',
    appId: '1:849051826489:android:61ccc173eadfa6ada110e8',
    messagingSenderId: '849051826489',
    projectId: 'control-asistencia-f6eb5',
    storageBucket: 'control-asistencia-f6eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99cmkkGYXoGd-iqa9drgH6BVwjQINEHI',
    appId: '1:849051826489:ios:eb7fe23e3dea6b95a110e8',
    messagingSenderId: '849051826489',
    projectId: 'control-asistencia-f6eb5',
    storageBucket: 'control-asistencia-f6eb5.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC99cmkkGYXoGd-iqa9drgH6BVwjQINEHI',
    appId: '1:849051826489:ios:eb7fe23e3dea6b95a110e8',
    messagingSenderId: '849051826489',
    projectId: 'control-asistencia-f6eb5',
    storageBucket: 'control-asistencia-f6eb5.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-s477TNVXm7uKDxIx_EiMC1PvwW7FCVY',
    appId: '1:849051826489:web:8a37d374d890b054a110e8',
    messagingSenderId: '849051826489',
    projectId: 'control-asistencia-f6eb5',
    authDomain: 'control-asistencia-f6eb5.firebaseapp.com',
    storageBucket: 'control-asistencia-f6eb5.firebasestorage.app',
    measurementId: 'G-H8D5CV79VC',
  );
}
